from __future__ import annotations

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
HEADER_DIR = ROOT / "include"
SOURCE = ROOT / "src" / "legacy_dm_x64.cpp"

if len(sys.argv) != 2:
    raise SystemExit("usage: generate_wrappers.py <output.inc>")

out_path = Path(sys.argv[1])
decl_text = "\n".join(
    p.read_text(encoding="utf-8-sig", errors="ignore")
    for p in sorted(HEADER_DIR.glob("legacy_dm_x64_decl*.inc"))
)
source_text = SOURCE.read_text(encoding="utf-8-sig", errors="ignore")

decl_re = re.compile(
    r"^\s*virtual\s+(?P<ret>.+?)\s+(?P<name>[A-Za-z_]\w*)\((?P<params>.*)\);\s*$",
    re.MULTILINE,
)
implemented = set(re.findall(r"\bdmsoft::([A-Za-z_]\w*)\s*\(", source_text))

invoke = {
    "long": "InvokeLong",
    "LONGLONG": "InvokeInt64",
    "float": "InvokeFloat",
    "double": "InvokeDouble",
    "const char *": "InvokeString",
}

def split_params(params: str) -> list[str]:
    params = params.strip()
    if not params or params == "void":
        return []
    # Legacy signatures contain no nested function-pointer/template parameters.
    return [p.strip() for p in params.split(",")]

def param_name(decl: str) -> str:
    m = re.search(r"([A-Za-z_]\w*)\s*(?:\[[^\]]*\])?\s*$", decl)
    if not m:
        raise ValueError(f"cannot parse parameter name: {decl!r}")
    return m.group(1)

generated: list[str] = [
    "/* AUTO-GENERATED by tools/generate_wrappers.py. Do not edit. */",
    "",
]
count = 0
for m in decl_re.finditer(decl_text):
    ret = " ".join(m.group("ret").split()).replace("char *", "char *")
    name = m.group("name")
    params = m.group("params").strip()
    if name in implemented:
        continue
    method = invoke.get(ret)
    if not method:
        raise ValueError(f"unsupported return type {ret!r} for {name}")
    args = split_params(params)
    arg_expr = ", ".join(f"A({param_name(p)})" for p in args)
    generated += [
        f"{ret} dmsoft::{name}({params})",
        "{",
        "    SetNativeError(P(impl), 0);",
        f'    return P(impl)->op.{method}("{name}", {{{arg_expr}}});',
        "}",
        "",
    ]
    count += 1

out_path.parent.mkdir(parents=True, exist_ok=True)
out_path.write_text("\n".join(generated), encoding="utf-8")
print(f"generated {count} wrappers -> {out_path}")
